/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "arbitro2_estr.v:1" *)
module arbitro2_estr(clk, empty, reset, \class , almost_full, pop_estr, push_estr);
  (* src = "arbitro2_estr.v:11" *)
  wire _00_;
  (* src = "arbitro2_estr.v:11" *)
  wire [3:0] _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  (* src = "arbitro2_estr.v:4" *)
  input [3:0] almost_full;
  (* src = "arbitro2_estr.v:3" *)
  input [1:0] \class ;
  (* src = "arbitro2_estr.v:2" *)
  input clk;
  (* src = "arbitro2_estr.v:2" *)
  input empty;
  (* src = "arbitro2_estr.v:5" *)
  output pop_estr;
  (* src = "arbitro2_estr.v:6" *)
  output [3:0] push_estr;
  (* src = "arbitro2_estr.v:2" *)
  input reset;
  NOT _11_ (
    .A(\class [1]),
    .Y(_02_)
  );
  NOT _12_ (
    .A(\class [0]),
    .Y(_03_)
  );
  NOR _13_ (
    .A(almost_full[3]),
    .B(almost_full[2]),
    .Y(_04_)
  );
  NOR _14_ (
    .A(almost_full[0]),
    .B(empty),
    .Y(_05_)
  );
  NOT _15_ (
    .A(_05_),
    .Y(_06_)
  );
  NOR _16_ (
    .A(almost_full[1]),
    .B(reset),
    .Y(_07_)
  );
  NAND _17_ (
    .A(_04_),
    .B(_07_),
    .Y(_08_)
  );
  NOR _18_ (
    .A(_06_),
    .B(_08_),
    .Y(_00_)
  );
  NAND _19_ (
    .A(_03_),
    .B(_00_),
    .Y(_09_)
  );
  NOR _20_ (
    .A(\class [1]),
    .B(_09_),
    .Y(_01_[0])
  );
  NAND _21_ (
    .A(\class [0]),
    .B(_00_),
    .Y(_10_)
  );
  NOR _22_ (
    .A(\class [1]),
    .B(_10_),
    .Y(_01_[1])
  );
  NOR _23_ (
    .A(_02_),
    .B(_09_),
    .Y(_01_[2])
  );
  NOR _24_ (
    .A(_02_),
    .B(_10_),
    .Y(_01_[3])
  );
  (* src = "arbitro2_estr.v:11" *)
  DFF _25_ (
    .C(clk),
    .D(_00_),
    .Q(pop_estr)
  );
  (* src = "arbitro2_estr.v:11" *)
  DFF _26_ (
    .C(clk),
    .D(_01_[0]),
    .Q(push_estr[0])
  );
  (* src = "arbitro2_estr.v:11" *)
  DFF _27_ (
    .C(clk),
    .D(_01_[1]),
    .Q(push_estr[1])
  );
  (* src = "arbitro2_estr.v:11" *)
  DFF _28_ (
    .C(clk),
    .D(_01_[2]),
    .Q(push_estr[2])
  );
  (* src = "arbitro2_estr.v:11" *)
  DFF _29_ (
    .C(clk),
    .D(_01_[3]),
    .Q(push_estr[3])
  );
endmodule
