/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "fsm_synth.v:1" *)
module fsm_synth(clk, reset, init, umbral_LH, empty_fifo_0, empty_fifo_1, empty_fifo_2, empty_fifo_3, empty_fifo_4, empty_fifo_5, empty_fifo_6, empty_fifo_7, state, nxt_state, umbral_LH_out, next_umbral_LH_out, idle_out);
  (* src = "fsm_synth.v:30" *)
  wire [2:0] _000_;
  (* src = "fsm_synth.v:30" *)
  wire [7:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  (* src = "fsm_synth.v:23" *)
  wire [7:0] FIFO_empties;
  (* src = "fsm_synth.v:4" *)
  input clk;
  (* src = "fsm_synth.v:8" *)
  input empty_fifo_0;
  (* src = "fsm_synth.v:9" *)
  input empty_fifo_1;
  (* src = "fsm_synth.v:10" *)
  input empty_fifo_2;
  (* src = "fsm_synth.v:11" *)
  input empty_fifo_3;
  (* src = "fsm_synth.v:12" *)
  input empty_fifo_4;
  (* src = "fsm_synth.v:13" *)
  input empty_fifo_5;
  (* src = "fsm_synth.v:14" *)
  input empty_fifo_6;
  (* src = "fsm_synth.v:15" *)
  input empty_fifo_7;
  (* src = "fsm_synth.v:21" *)
  output idle_out;
  (* src = "fsm_synth.v:6" *)
  input init;
  (* src = "fsm_synth.v:19" *)
  output [7:0] next_umbral_LH_out;
  (* src = "fsm_synth.v:17" *)
  output [2:0] nxt_state;
  (* src = "fsm_synth.v:5" *)
  input reset;
  (* src = "fsm_synth.v:16" *)
  output [2:0] state;
  (* src = "fsm_synth.v:7" *)
  input [7:0] umbral_LH;
  (* src = "fsm_synth.v:18" *)
  output [7:0] umbral_LH_out;
  NOT _070_ (
    .A(state[0]),
    .Y(_027_)
  );
  NOT _071_ (
    .A(state[1]),
    .Y(_028_)
  );
  NOT _072_ (
    .A(reset),
    .Y(_029_)
  );
  NOT _073_ (
    .A(umbral_LH_out[0]),
    .Y(_030_)
  );
  NOT _074_ (
    .A(umbral_LH[0]),
    .Y(_031_)
  );
  NOT _075_ (
    .A(umbral_LH_out[1]),
    .Y(_032_)
  );
  NOT _076_ (
    .A(umbral_LH[1]),
    .Y(_033_)
  );
  NOT _077_ (
    .A(umbral_LH_out[2]),
    .Y(_034_)
  );
  NOT _078_ (
    .A(umbral_LH[2]),
    .Y(_035_)
  );
  NOT _079_ (
    .A(umbral_LH_out[3]),
    .Y(_036_)
  );
  NOT _080_ (
    .A(umbral_LH[3]),
    .Y(_037_)
  );
  NOT _081_ (
    .A(umbral_LH_out[4]),
    .Y(_038_)
  );
  NOT _082_ (
    .A(umbral_LH[4]),
    .Y(_039_)
  );
  NOT _083_ (
    .A(umbral_LH_out[5]),
    .Y(_040_)
  );
  NOT _084_ (
    .A(umbral_LH[5]),
    .Y(_041_)
  );
  NOT _085_ (
    .A(umbral_LH_out[6]),
    .Y(_042_)
  );
  NOT _086_ (
    .A(umbral_LH[6]),
    .Y(_043_)
  );
  NOT _087_ (
    .A(umbral_LH_out[7]),
    .Y(_044_)
  );
  NOT _088_ (
    .A(umbral_LH[7]),
    .Y(_045_)
  );
  NOT _089_ (
    .A(init),
    .Y(_046_)
  );
  NOR _090_ (
    .A(_027_),
    .B(state[2]),
    .Y(_047_)
  );
  NAND _091_ (
    .A(state[0]),
    .B(_028_),
    .Y(_048_)
  );
  NOR _092_ (
    .A(state[2]),
    .B(_048_),
    .Y(_049_)
  );
  NAND _093_ (
    .A(_028_),
    .B(_047_),
    .Y(_050_)
  );
  NOR _094_ (
    .A(_029_),
    .B(init),
    .Y(_051_)
  );
  NAND _095_ (
    .A(reset),
    .B(_046_),
    .Y(_052_)
  );
  NOR _096_ (
    .A(_050_),
    .B(_052_),
    .Y(_053_)
  );
  NAND _097_ (
    .A(_049_),
    .B(_051_),
    .Y(_054_)
  );
  NOR _098_ (
    .A(_031_),
    .B(_054_),
    .Y(_055_)
  );
  NOR _099_ (
    .A(_030_),
    .B(_053_),
    .Y(_056_)
  );
  NOR _100_ (
    .A(_055_),
    .B(_056_),
    .Y(_057_)
  );
  NOT _101_ (
    .A(_057_),
    .Y(next_umbral_LH_out[0])
  );
  NOR _102_ (
    .A(_033_),
    .B(_054_),
    .Y(_058_)
  );
  NOR _103_ (
    .A(_032_),
    .B(_053_),
    .Y(_059_)
  );
  NOR _104_ (
    .A(_058_),
    .B(_059_),
    .Y(_060_)
  );
  NOT _105_ (
    .A(_060_),
    .Y(next_umbral_LH_out[1])
  );
  NOR _106_ (
    .A(_035_),
    .B(_054_),
    .Y(_061_)
  );
  NOR _107_ (
    .A(_034_),
    .B(_053_),
    .Y(_062_)
  );
  NOR _108_ (
    .A(_061_),
    .B(_062_),
    .Y(_063_)
  );
  NOT _109_ (
    .A(_063_),
    .Y(next_umbral_LH_out[2])
  );
  NOR _110_ (
    .A(_037_),
    .B(_054_),
    .Y(_064_)
  );
  NOR _111_ (
    .A(_036_),
    .B(_053_),
    .Y(_065_)
  );
  NOR _112_ (
    .A(_064_),
    .B(_065_),
    .Y(_066_)
  );
  NOT _113_ (
    .A(_066_),
    .Y(next_umbral_LH_out[3])
  );
  NOR _114_ (
    .A(_039_),
    .B(_054_),
    .Y(_067_)
  );
  NOR _115_ (
    .A(_038_),
    .B(_053_),
    .Y(_068_)
  );
  NOR _116_ (
    .A(_067_),
    .B(_068_),
    .Y(_069_)
  );
  NOT _117_ (
    .A(_069_),
    .Y(next_umbral_LH_out[4])
  );
  NOR _118_ (
    .A(_041_),
    .B(_054_),
    .Y(_002_)
  );
  NOR _119_ (
    .A(_040_),
    .B(_053_),
    .Y(_003_)
  );
  NOR _120_ (
    .A(_002_),
    .B(_003_),
    .Y(_004_)
  );
  NOT _121_ (
    .A(_004_),
    .Y(next_umbral_LH_out[5])
  );
  NOR _122_ (
    .A(_043_),
    .B(_054_),
    .Y(_005_)
  );
  NOR _123_ (
    .A(_042_),
    .B(_053_),
    .Y(_006_)
  );
  NOR _124_ (
    .A(_005_),
    .B(_006_),
    .Y(_007_)
  );
  NOT _125_ (
    .A(_007_),
    .Y(next_umbral_LH_out[6])
  );
  NOR _126_ (
    .A(_045_),
    .B(_054_),
    .Y(_008_)
  );
  NOR _127_ (
    .A(_044_),
    .B(_053_),
    .Y(_009_)
  );
  NOR _128_ (
    .A(_008_),
    .B(_009_),
    .Y(_010_)
  );
  NOT _129_ (
    .A(_010_),
    .Y(next_umbral_LH_out[7])
  );
  NOR _130_ (
    .A(state[0]),
    .B(state[2]),
    .Y(_011_)
  );
  NOR _131_ (
    .A(state[1]),
    .B(_029_),
    .Y(_012_)
  );
  NAND _132_ (
    .A(_011_),
    .B(_012_),
    .Y(_013_)
  );
  NAND _133_ (
    .A(_054_),
    .B(_013_),
    .Y(nxt_state[0])
  );
  NAND _134_ (
    .A(state[1]),
    .B(_011_),
    .Y(_014_)
  );
  NAND _135_ (
    .A(empty_fifo_4),
    .B(empty_fifo_5),
    .Y(_015_)
  );
  NAND _136_ (
    .A(empty_fifo_6),
    .B(empty_fifo_7),
    .Y(_016_)
  );
  NOR _137_ (
    .A(_015_),
    .B(_016_),
    .Y(_017_)
  );
  NAND _138_ (
    .A(empty_fifo_0),
    .B(empty_fifo_1),
    .Y(_018_)
  );
  NAND _139_ (
    .A(empty_fifo_2),
    .B(empty_fifo_3),
    .Y(_019_)
  );
  NOR _140_ (
    .A(_018_),
    .B(_019_),
    .Y(_020_)
  );
  NAND _141_ (
    .A(_017_),
    .B(_020_),
    .Y(_021_)
  );
  NOR _142_ (
    .A(_014_),
    .B(_021_),
    .Y(_022_)
  );
  NAND _143_ (
    .A(init),
    .B(_049_),
    .Y(_023_)
  );
  NOT _144_ (
    .A(_023_),
    .Y(_024_)
  );
  NOR _145_ (
    .A(_022_),
    .B(_024_),
    .Y(_025_)
  );
  NOT _146_ (
    .A(_025_),
    .Y(nxt_state[1])
  );
  NOR _147_ (
    .A(_029_),
    .B(_025_),
    .Y(_000_[1])
  );
  NAND _148_ (
    .A(reset),
    .B(_021_),
    .Y(_026_)
  );
  NOR _149_ (
    .A(_014_),
    .B(_026_),
    .Y(nxt_state[2])
  );
  NOR _150_ (
    .A(_029_),
    .B(_057_),
    .Y(_001_[0])
  );
  NOR _151_ (
    .A(_029_),
    .B(_060_),
    .Y(_001_[1])
  );
  NOR _152_ (
    .A(_029_),
    .B(_063_),
    .Y(_001_[2])
  );
  NOR _153_ (
    .A(_029_),
    .B(_066_),
    .Y(_001_[3])
  );
  NOR _154_ (
    .A(_029_),
    .B(_069_),
    .Y(_001_[4])
  );
  NOR _155_ (
    .A(_029_),
    .B(_004_),
    .Y(_001_[5])
  );
  NOR _156_ (
    .A(_029_),
    .B(_007_),
    .Y(_001_[6])
  );
  NOR _157_ (
    .A(_029_),
    .B(_010_),
    .Y(_001_[7])
  );
  NAND _158_ (
    .A(_054_),
    .B(_013_),
    .Y(_000_[0])
  );
  NOR _159_ (
    .A(_014_),
    .B(_026_),
    .Y(_000_[2])
  );
  (* src = "fsm_synth.v:30" *)
  DFF _160_ (
    .C(clk),
    .D(_000_[0]),
    .Q(state[0])
  );
  (* src = "fsm_synth.v:30" *)
  DFF _161_ (
    .C(clk),
    .D(_000_[1]),
    .Q(state[1])
  );
  (* src = "fsm_synth.v:30" *)
  DFF _162_ (
    .C(clk),
    .D(_000_[2]),
    .Q(state[2])
  );
  (* src = "fsm_synth.v:30" *)
  DFF _163_ (
    .C(clk),
    .D(_001_[0]),
    .Q(umbral_LH_out[0])
  );
  (* src = "fsm_synth.v:30" *)
  DFF _164_ (
    .C(clk),
    .D(_001_[1]),
    .Q(umbral_LH_out[1])
  );
  (* src = "fsm_synth.v:30" *)
  DFF _165_ (
    .C(clk),
    .D(_001_[2]),
    .Q(umbral_LH_out[2])
  );
  (* src = "fsm_synth.v:30" *)
  DFF _166_ (
    .C(clk),
    .D(_001_[3]),
    .Q(umbral_LH_out[3])
  );
  (* src = "fsm_synth.v:30" *)
  DFF _167_ (
    .C(clk),
    .D(_001_[4]),
    .Q(umbral_LH_out[4])
  );
  (* src = "fsm_synth.v:30" *)
  DFF _168_ (
    .C(clk),
    .D(_001_[5]),
    .Q(umbral_LH_out[5])
  );
  (* src = "fsm_synth.v:30" *)
  DFF _169_ (
    .C(clk),
    .D(_001_[6]),
    .Q(umbral_LH_out[6])
  );
  (* src = "fsm_synth.v:30" *)
  DFF _170_ (
    .C(clk),
    .D(_001_[7]),
    .Q(umbral_LH_out[7])
  );
  assign FIFO_empties = { empty_fifo_7, empty_fifo_6, empty_fifo_5, empty_fifo_4, empty_fifo_3, empty_fifo_2, empty_fifo_1, empty_fifo_0 };
  assign idle_out = 1'h0;
endmodule
